name: Build Debian Packages (Dockerized Bookworm)

on:
  push:
  pull_request:
  release:

jobs:
  build:
    runs-on: ubuntu-latest # We use an Ubuntu runner to execute Docker
    container:
      image: debian:bookworm-slim # Or a more specific Bookworm image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends debhelper devscripts build-essential autoconf automake libtool libgtk-3-dev libpulse-dev

      - name: Generate Autotools files (if needed)
        run: |
          autoreconf -i

      - name: Build source package
        run: dpkg-buildpackage -S -uc -us -sa

      - name: Build binary package
        run: dpkg-buildpackage -b -uc -us

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          mv ../*.{dsc,changes,tar.gz,debian.tar.xz,deb} artifacts/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: artifacts/
